package com.hopl.service;

import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;

@Service
public class PdfExportService {

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 20, Font.BOLD, new Color(31, 41, 55));
    private static final Font HEADING_FONT = new Font(Font.HELVETICA, 14, Font.BOLD, new Color(55, 65, 81));
    private static final Font BODY_FONT = new Font(Font.HELVETICA, 11, Font.NORMAL, new Color(75, 85, 99));
    private static final Font SMALL_FONT = new Font(Font.HELVETICA, 9, Font.ITALIC, new Color(156, 163, 175));

    /**
     * Exports document content to a professional PDF.
     *
     * @param title document title
     * @param content markdown/text content
     * @param businessName the business name for the footer
     * @return PDF bytes
     */
    public byte[] exportToPdf(String title, String content, String businessName) {
        try (ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4, 60, 60, 50, 50);
            PdfWriter.getInstance(document, baos);
            document.open();

            Paragraph titlePara = new Paragraph(title, TITLE_FONT);
            titlePara.setSpacingAfter(8);
            document.add(titlePara);

            Paragraph meta = new Paragraph(
                    "Generated for " + businessName + " | " + LocalDate.now() + " | HOPL Compliance Scanner",
                    SMALL_FONT);
            meta.setSpacingAfter(20);
            document.add(meta);

            document.add(new Chunk(new com.lowagie.text.pdf.draw.LineSeparator()));
            document.add(Chunk.NEWLINE);

            String[] lines = content.split("\n");
            for (String line : lines) {
                String trimmed = line.trim();
                if (trimmed.isEmpty()) {
                    document.add(Chunk.NEWLINE);
                } else if (trimmed.startsWith("# ")) {
                    Paragraph h = new Paragraph(trimmed.substring(2), TITLE_FONT);
                    h.setSpacingBefore(15);
                    h.setSpacingAfter(8);
                    document.add(h);
                } else if (trimmed.startsWith("## ")) {
                    Paragraph h = new Paragraph(trimmed.substring(3), HEADING_FONT);
                    h.setSpacingBefore(12);
                    h.setSpacingAfter(6);
                    document.add(h);
                } else if (trimmed.startsWith("### ")) {
                    Font subheading = new Font(Font.HELVETICA, 12, Font.BOLD, new Color(75, 85, 99));
                    Paragraph h = new Paragraph(trimmed.substring(4), subheading);
                    h.setSpacingBefore(10);
                    h.setSpacingAfter(5);
                    document.add(h);
                } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
                    Paragraph bullet = new Paragraph("  \u2022  " + trimmed.substring(2), BODY_FONT);
                    bullet.setIndentationLeft(20);
                    document.add(bullet);
                } else {
                    Paragraph p = new Paragraph(trimmed, BODY_FONT);
                    p.setSpacingAfter(4);
                    p.setLeading(16);
                    document.add(p);
                }
            }

            document.add(Chunk.NEWLINE);
            document.add(new Chunk(new com.lowagie.text.pdf.draw.LineSeparator()));
            Paragraph footer = new Paragraph(
                    "This document was generated by HOPL (hopl.app). It is for informational purposes only and does not constitute legal advice.",
                    SMALL_FONT);
            footer.setSpacingBefore(10);
            document.add(footer);

            document.close();
            return baos.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF", e);
        }
    }
}
